#ifndef UNTITLED_CONSTANTS_H
#define UNTITLED_CONSTANTS_H


#define MUSEUM_SHM_ID   1
#define MUSEUM_SEM_ID   1
#define MUSEUM_CAPACITY  10
#define MUSEUM_DOORS   3
#define DOOR_MAX_RESPONSE_TIME 1
#define PERSON_MAX_RIDE_TIME 10


#endif //UNTITLED_CONSTANTS_H
